export default  [
    {
      id:1,
      category:"Computer",
      title:"Aliquam lobortis est turpis mauris",
      slug:"product-1",
      description:"Canon's press material for the EOS 5D states that it 'defines (a) new D-SLR category', while we're not typically too concerned with marketing talk this particular statement is clearly pretty accurate...",
      image:"http://sinrato.mallthemes.com/wp-content/uploads/2018/12/product15-400x400.jpg",
      brand:"Brand",
    }, 
    {
      id:2,
      title:"Aliquam lobortis est turpis mauris",
      category:"Video Games",
      slug:"product-2",
      description:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic id eum minus quam odit corporis harum eaque recusandae quia incidunt, excepturi maiores placeat magnam adipisci quisquam, iste nostrum ut facere!",
      image:"http://sinrato.mallthemes.com/wp-content/uploads/2018/12/product15-400x400.jpg",
      brand:"Brand",
    }, 
    {
      id:3,
      title:"Aliquam lobortis est turpis mauris",
      category:"Game",
      slug:"product-3",
      description:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic id eum minus quam odit corporis harum eaque recusandae quia incidunt, excepturi maiores placeat magnam adipisci quisquam, iste nostrum ut facere!",
      image:"http://sinrato.mallthemes.com/wp-content/uploads/2018/12/product15-400x400.jpg",
      brand:"Brand",
    }, 
    {
      id:4,
      title:"Aliquam lobortis est turpis mauris",
      category:"Category 4",
      slug:"product-4",
      description:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic id eum minus quam odit corporis harum eaque recusandae quia incidunt, excepturi maiores placeat magnam adipisci quisquam, iste nostrum ut facere!",
      image:"http://sinrato.mallthemes.com/wp-content/uploads/2018/12/product15-400x400.jpg",
      brand:"Brand",
    }, 
    {
      id:1,
      category:"Computer",
      title:"Aliquam lobortis est turpis mauris",
      slug:"product-1",
      description:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic id eum minus quam odit corporis harum eaque recusandae quia incidunt, excepturi maiores placeat magnam adipisci quisquam, iste nostrum ut facere!",
      image:"http://sinrato.mallthemes.com/wp-content/uploads/2018/12/product15-400x400.jpg",
      brand:"Brand",
    }, 
    {
      id:2,
      title:"Aliquam lobortis est turpis mauris",
      category:"Video Games",
      slug:"product-2",
      description:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic id eum minus quam odit corporis harum eaque recusandae quia incidunt, excepturi maiores placeat magnam adipisci quisquam, iste nostrum ut facere!",
      image:"http://sinrato.mallthemes.com/wp-content/uploads/2018/12/product15-400x400.jpg",
      brand:"Brand",
    }, 
    {
      id:3,
      title:"Aliquam lobortis est turpis mauris",
      category:"Game",
      slug:"product-3",
      description:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic id eum minus quam odit corporis harum eaque recusandae quia incidunt, excepturi maiores placeat magnam adipisci quisquam, iste nostrum ut facere!",
      image:"http://sinrato.mallthemes.com/wp-content/uploads/2018/12/product15-400x400.jpg",
      brand:"Brand",
    }, 
    {
      id:4,
      title:"Aliquam lobortis est turpis mauris",
      category:"Category 4",
      slug:"product-4",
      description:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic id eum minus quam odit corporis harum eaque recusandae quia incidunt, excepturi maiores placeat magnam adipisci quisquam, iste nostrum ut facere!",
      image:"http://sinrato.mallthemes.com/wp-content/uploads/2018/12/product15-400x400.jpg",
      brand:"Brand",
    }, 
  ];